format='\[ $directory\] $character '
right_format='\[ $all\]'
add_newline = false

[line_break]
disabled = true

[character]
format = '[ï](green bold)'

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 2
